name: ise-agent-__AGENT_SUFFIX__

services:
  ise-agent:
    image: ghcr.io/duosecurity/ise-agent:latest
    pull_policy: never
    container_name: __CONTAINER_NAME__
    restart: always
    env_file: .env
    stop_grace_period: 30s
    volumes:
      - ./certs:/app/certs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
